### ISSUE TITLE
bug: Restarting Revolt via tray icon opens default electron application

### ISSUE THREAD

**Issue by stationaryStation** [revoltchat/desktop#87]
### What happened?

If you restart the revolt desktop-application via the tray icon you wont get the revolt interface but instead the default electron application.

revolt-desktop build cca97f9 (master)
revolt.js version 6.0.0-rc-26.0
native version 1.0.4

OS: Arch Linux x86_64
Host: Lenovo Thinkpad P43s 

![Left: Revolt restarted via Tray](https://i.imgur.com/uVDzJLA.png)

**Comment by I2rys** [comment]
This bug is already fixed in the newest version.

**Comment by insertish** [comment]
Doesn't affect Windows on version 1.0.5.

**Comment by KittyKatJas** [comment]
I can confirm it isn't fixed on linux.
Using the latest update.

https://user-images.githubusercontent.com/73664232/182042504-6e7b893b-9988-4141-9fbd-750d1d66cfbc.mp4

**Comment by EndLordMC** [comment]
This still happens with the desktop client in Arch linux. It also happens when Revolt automatically starts upon login.
